# Pytorch基本操作考察

In [2]:
import torch

## 基本操作实验1
使用 𝐓𝐞𝐧𝐬𝐨𝐫 初始化一个 𝟏×𝟑 的矩阵 𝑴 和一个 𝟐×𝟏 的矩阵 𝑵，对两矩阵进行减法操作（要求实现三种不同的形式），给出结果并分析三种方式的不同（如果出现报错，分析报错的原因），同时需要指出在计算过程中发生了什么

计算过程中发生了什么？\
广播操作

使用第三种减法操作会报错，因为是原地操作，当进行广播后，计算结果和原矩阵的形状不同，所以会报错

In [3]:
M=torch.rand(1,3)
N=torch.rand(2,1)
print(M)
print(N)
#加法形式1
print(M+N)
#加法形式2
print(torch.add(M,N))

tensor([[0.8688, 0.1230, 0.0368]])
tensor([[0.4914],
        [0.8077]])
tensor([[1.3602, 0.6144, 0.5282],
        [1.6765, 0.9307, 0.8445]])
tensor([[1.3602, 0.6144, 0.5282],
        [1.6765, 0.9307, 0.8445]])


In [4]:
#加法形式3
N.add_(M)
print(N)
"""
方法1和方法2都触发了广播机制，因为两个tensor的形状不同
方法3不满足触发广播机制的条件，因为tensor形状不同，所以报错
"""

RuntimeError: output with shape [2, 1] doesn't match the broadcast shape [2, 3]

## 基本操作实验2
1) 利用 𝐓𝐞𝐧𝐬𝐨𝐫 创建两个大小分别 𝟑×𝟐 和 𝟒×𝟐 的随机数矩阵 𝑷 和 𝑸 ，要求服从均值为0，标准差0.01为的正态分布 \
2) 对第二步得到的矩阵 𝑸 进行形状变换得到 𝑸 的转置 $𝑸^𝑻$  \
3) 对上述得到的矩阵 𝑷 和矩阵 $𝑸^𝑻$ 求内积

In [5]:
P=torch.normal(0,0.01,size=(3,2))
Q=torch.normal(0,0.01,size=(4,2))
print(P)
print(Q)

tensor([[ 0.0129, -0.0302],
        [ 0.0008, -0.0186],
        [ 0.0070,  0.0052]])
tensor([[ 0.0106, -0.0061],
        [-0.0024,  0.0074],
        [-0.0132,  0.0051],
        [ 0.0123,  0.0003]])


In [6]:
Q_T=torch.t(Q)
print(Q_T)

tensor([[ 0.0106, -0.0024, -0.0132,  0.0123],
        [-0.0061,  0.0074,  0.0051,  0.0003]])


In [7]:
#只能使用matmul方法 不能使用dot方法 dot方法只能计算一维tensor
print(torch.matmul(P,Q_T))

tensor([[ 3.1986e-04, -2.5523e-04, -3.2358e-04,  1.5058e-04],
        [ 1.2197e-04, -1.4029e-04, -1.0570e-04,  5.5214e-06],
        [ 4.2378e-05,  2.1580e-05, -6.5687e-05,  8.6870e-05]])


## 基本操作实验3
给定公式$𝑦_3=𝑦_1+𝑦_2=𝑥^2+𝑥^3$，且 $𝑥=1$。利用学习所得到的Tensor的相关知识，求$𝑦_3$对的梯度𝑥，即$𝑑𝑦_3$/$𝑑𝑥$。要求在计算过程中，在计算 $𝑥^3$ 时中断梯度的追踪，观察结果并进行原因分析

$x^3$的梯度是2而不是5的原因：\
由于 $y_2$的定义是被torch.no_grad():包裹的，所以与$y_2$有关的梯度是不会回传的，只有与$y_1$有关的梯度才会回传，即$x^2$对 $x$的梯度。\
而y2.requires_grad=False，所以不能调用 y2.backward()，会报错

In [8]:
x=torch.ones(2,2,requires_grad=True)
y1=x**2
with torch.no_grad():
    y2=x**3
# y2=x**3
y3=y1+y2
out=y3.mean()
out.backward()
print(x.grad)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])


In [9]:
#如果y2=x**3这部分被with torch.no_grad()包裹起来 这部分就不进行track操作
#如果没被包裹 那么求梯度的时候 y3=x**2+x**3 x=1时 求偏导为5/4
#若包裹 y3=x**2 x=1 求偏导为 1/2

In [1]:
import torch.nn as nn

In [ ]:
nn.AvgPool2d